### ISSUE TITLE
Token Leak

### ISSUE THREAD

**Issue by MM-coder** [TYPO3GmbH/elasticorn#16]
You appear to have leaked your Google Maps token at
https://raw.githubusercontent.com/TYPO3GmbH/elasticorn/3bdbafafd81fb326a435681533d576d27bcfe14a/docs/index.html

I'd highly suggest you remove it, and delete the git history

Hope I can help
Mauro M.

**Comment by susannemoog** [comment]
Thanks for the report. However, the token is not a valid token - therefore the history does not need to be adjusted. I'm closing this issue here.
